#String in built functions
#1.capitalize()
s = 'siddesh'
print(s.capitalize())
#2.length()
print(len(s))
#3.center()
print(s.center(30,'*'))
#4.endswith()
print(s.endswith('h'))
#5.find()
print(s.find('e'))
#6.rfind()
print(s.rfind('s'))
#7.lower()
print(s.lower())
#8.upper()
print(s.upper())
#9.isaplha()
print(s.isalpha())
#10.isdigit()
print(s.isdigit())
#11.isascii()
print(s.isascii())
#12.isdecimal()
print(s.isdecimal())
#13.isalnum()
print(s.isalnum())
